services:
  server:
    container_name: ${PROJECT_NAME}-nginx
    build: ./nginx
    command: nginx -g "daemon off;"
    # volumes:
    #   - ./srv-data:/data/www
    ports:
      - ${NGINX_PORT}:8080
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/conf.d
          target: /etc/nginx/conf.d

  frontend:
    container_name: ${PROJECT_NAME}-vue
    build: ./frontend
    command: npm run dev -- --host=0.0.0.0
    environment: 
      CHOKIDAR_USEPOLLING: true
      BACKEND_URL: ${PROJECT_NAME}-django:8080
    ports:
      - ${VUE_PORT}:5173
    volumes:
      - ./frontend:/app
      - ignore:/app/node_modules

  backend:
    container_name: ${PROJECT_NAME}-django 
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000 
    # volumes: 
    #   - ./backend/server:/server
    ports:
      - ${DJANGO_PORT}:8080

volumes:
  ignore:
