version: '3'

env:
  DOCKER_CLI_HINTS: false

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  default:
    cmds:
      - task: up

  up:
    desc: "server up"
    cmds:
      - docker compose up -d

  down:
    desc: "server down"
    cmds:
      - docker compose down
  
  watch:
    desc: "server watch"
    cmds:
      - docker compose watch

  restart:
    desc: "server restart"
    cmds:
      - task: down
      - task: up

  reload:
    desc: "nginx reload"
    cmds:
      - docker exec -it {{.PROJECT_NAME}}-nginx nginx -s reload

