# Generated by Django 5.2 on 2025-05-06 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.TextField(help_text='Название', verbose_name='Название')),
                ('description', models.TextField(help_text='Описание', verbose_name='Описание')),
                ('time', models.TextField(help_text='Время для реализации', null=True, verbose_name='Время для реализации')),
                ('instruction', models.TextField(help_text='Инструкция', null=True, verbose_name='Инструкция')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
